service: devops-project

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 256
  timeout: 30

functions:
  add:
    handler: app/calculator.add
    events:
      - http:
          method: post
          path: add
