name: pr-build-deploy

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
      - name: Check code formatting (black)
        run: black --check app tests
      - name: Check imports ordering (isort)
        run: isort --check app tests
      - name: SAST (bandit)
        run: bandit -r app tests
      - name: Unit tests (pytest)
        run: pytest

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Serverless framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.DEV_ACCESS_KEY_ID }} --secret ${{ secrets.DEV_SECRET_ACCESS_KEY }}
      - name: Deploy app on AWS
        run: sls deploy --stage dev
